# Generated by Django 4.2.7 on 2023-11-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_body_alter_books_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='images',
            field=models.ImageField(null=True, upload_to='books/images'),
        ),
        migrations.AlterField(
            model_name='books',
            name='body',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
